#http://cesarbruschetta.appspot.com/
#http://appengine.google.com/
application: cesarbruschetta
version: 1-5
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never  

- url: /hello
  script: helloworld.py 

- url: /time
  script: time.py

- url: /prefs
  script: prefs.py
  login: required

- url: /password
  script: passwordgenerator.py

- url: /passwordGenRequest
  script: passwordgenerator.py

- url: /book
  script: bookmarksbin.py

- url: /.*
  script: index.py

