#http://cesar-bruschetta.appspot.com/
#http://appengine.google.com/
application: cesar-bruschetta
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never  

# Your custom handler goes here (see next step)
# - url: /admin/models.*
#   script: handlers.admin.app
#   secure: always

- url: /hello
  script: helloworld.py 

- url: /time
  script: timepage.py

- url: /prefs
  script: prefs.py
  login: required

- url: /password
  script: passwordgenerator.py

- url: /passwordGenRequest
  script: passwordgenerator.py

- url: /book
  script: bookmarksbin.py

- url: /.*
  script: index.py